# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d793f7539017193cf25cf9658a86b05decef94dde72e70d22b7ebf81dfdd7b76433ff42162cf7a5e3cb9350846a16d055cb96031ec886dd4ff367c9d986bbce0

test:
  secret_key_base: 39f9fec77d8b237195d903b99a5af2799a71f25e36c92fdffd14376ac1f6c900c61340eb6e0c8e956017b3761ffde75c4b0e4544e950f3f5ffd8649b1ef15187

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
